version: '2'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - MONGO_URL=mongo:27017
    ports: 
      - "8080:8080"
    networks:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
networks:
  backend: